version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: app-container
    image: typescript-clean-architecture-implementation
    build: .
    restart: always
    volumes:
      - ./dist:/usr/src/typescript-clean-architecture-implementation/dist
      - ./package.json:/usr/src/typescript-clean-architecture-implementation/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    command: npm run debug
    links:
      - mongo